/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module atriumapp;

private
{
    import std.stdio;
    import std.conv;
    import std.string;
    import std.process;
    import std.algorithm;
    import std.math;

    import derelict.util.compat;
    import derelict.sdl.sdl;
    import derelict.opengl.gl;
    import derelict.opengl.glu;
    import derelict.opengl.glext;
    import derelict.freetype.ft;

    import dlib.math.vector;
    import dlib.math.matrix4x4;
    import dlib.math.matrix3x3;
    import dlib.math.quaternion;
    import dlib.math.utils;
    import dlib.geometry.ray;
    import dlib.geometry.utils;
    import dlib.geometry.plane;
    import dlib.geometry.sphere;
    import dlib.geometry.aabb;
    import dlib.geometry.obb;
    import dlib.geometry.intersection;
    import dlib.image.image;
    import dlib.image.color;
    import dlib.image.io.png;
    
    import dlib.geometry.triangle;
    import dlib.geometry.trimesh;

    import atrium.all;

    import obj;
    import utils;
    import dat;

    import level;
}

void drawActiveHierarchy(BVHNode node, ref Sphere sphere)
{
    Vector3f cn;
    float pd;
    if (node.aabb.intersectsSphere(sphere, cn, pd))
    {
        if (node.child[0] !is null)
            node.child[0].drawActiveHierarchy(sphere);
        if (node.child[1] !is null)
            node.child[1].drawActiveHierarchy(sphere);

        drawAABB(node.aabb);
    }
}
    
void drawTriMesh(TriMesh m, bool wireframe = false)
{
    glPushMatrix();
    if (wireframe)
        glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
    glBegin(GL_TRIANGLES);
    foreach (fg; m.facegroups)
    foreach (ti; fg.indices)
    {
        glNormal3fv(m.normals[ti.a].arrayof.ptr);
        glVertex3fv(m.vertices[ti.a].arrayof.ptr);
                
        glNormal3fv(m.normals[ti.b].arrayof.ptr);
        glVertex3fv(m.vertices[ti.b].arrayof.ptr);
                
        glNormal3fv(m.normals[ti.c].arrayof.ptr);
        glVertex3fv(m.vertices[ti.c].arrayof.ptr);
    }
    glEnd();
    if (wireframe)
        glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
    glPopMatrix();
}

class DatRenderer
{
    uint[int] lists;
    DatObject obj;

    this(DatObject obj)
    {
        this.obj = obj;
        foreach(matIndex, mat; obj.materialByIndex)
        {
            uint list = glGenLists(1);
            glNewList(list, GL_COMPILE);
            //mat.bind(0.0);
            glBegin(GL_TRIANGLES);
            foreach(tri; obj.tris)
            {
                if (tri.materialIndex == matIndex)
                {                
                    glNormal3fv(tri.normal.arrayof.ptr);
                    //glNormal3fv(tri.n[0].arrayof.ptr);
                    glMultiTexCoord2fvARB(GL_TEXTURE0_ARB, tri.t1[0].arrayof.ptr);
                    glMultiTexCoord2fvARB(GL_TEXTURE1_ARB, tri.t2[0].arrayof.ptr);
                    glVertex3fv(tri.v[0].arrayof.ptr);
            
                    //glNormal3fv(tri.n[1].arrayof.ptr);
                    glMultiTexCoord2fvARB(GL_TEXTURE0_ARB, tri.t1[1].arrayof.ptr);
                    glMultiTexCoord2fvARB(GL_TEXTURE1_ARB, tri.t2[1].arrayof.ptr);
                    glVertex3fv(tri.v[1].arrayof.ptr);
            
                    //glNormal3fv(tri.n[2].arrayof.ptr);
                    glMultiTexCoord2fvARB(GL_TEXTURE0_ARB, tri.t1[2].arrayof.ptr);
                    glMultiTexCoord2fvARB(GL_TEXTURE1_ARB, tri.t2[2].arrayof.ptr);
                    glVertex3fv(tri.v[2].arrayof.ptr);
                }
            }
            glEnd();
            //mat.unbind();
            glEndList();
            lists[matIndex] = list;
        }
    }
    
    void render()
    {
        foreach(matIndex, mat; obj.materialByIndex)
        {
            uint list = lists[matIndex];
            mat.bind(0.0);
            glCallList(list);
            mat.unbind();
        }
    }
}

class AtriumApp: Application
{
    Font ftMain;
    Text txtInfo;
    Text txtFPS;
    
    Config cfg;

    Level currentLevel;

    this(uint w, uint h, string caption)
    {
        cfg = new Config();
        readConfiguration(cfg, "settings.conf");
        string videoWidth = cfg.get("video.width");
        string videoHeight = cfg.get("video.height");
        w = (videoWidth.length > 0)? videoWidth.to!uint : w;
        h = (videoHeight.length > 0)? videoHeight.to!uint : h;
    
        super(w, h, caption);

        glClearColor(0.4f, 0.4f, 0.4f, 1.0f);
        glEnable(GL_LIGHTING);
        glEnable(GL_LIGHT0);

        manager.bindActionToEvent(EventType.KeyDown, &onKeyDown);

        // Create font and text
        ftMain = new Font();
        ftMain.init("data/fonts/droid/DroidSans.ttf", 14);

        txtInfo = new Text(ftMain);
        txtInfo.setPos(16, manager.window_width-32);

        txtFPS = new Text(ftMain);
        txtFPS.setPos(16, 16);

        manager.bindActionToEvent(EventType.Resize, &onResize);
        manager.bindActionToEvent(EventType.MouseButtonDown, &onMouseButtonDown);

        currentLevel = new Level("data/area0/area0.dat", manager);
    }

    void onResize()
    {
        txtInfo.setPos(16, manager.window_height-32); 
    }

    void onMouseButtonDown()
    {

    }

    override void onUpdate()
    {
        currentLevel.run();
    }
    
    float scaled(float f)
    {
        return f / (1.0f / 60.0f);
    }

    void onKeyDown()
    {
        if (manager.event_key == SDLK_ESCAPE)
        {
            manager.running = false;
        }
    }
}


