/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module engine.logic;

import std.stdio;
import engine.core.appmanager;
import engine.ui.font;
import engine.locale;

/*
 * Some kind of level/room system
 */

class GameLogicManager
{
    AppManager appManager;

    GameRoom currentRoom;
    GameRoom previousRoom;
    GameRoom[string] rooms;
    string nextRoom = "";
    bool freeCurrent;
    bool loadNext;

    Font fontMain;
    int mainFontHeight = 14;

    dstring[string] dictionary;

    //bool gameIsPaused = false;

    this(AppManager m)
    {
        appManager = m;
        rooms["_exit_"] = new ExitRoom("_exit_", this);
        rooms["_current_room_"] = currentRoom;

        fontMain = new Font();
        fontMain.init("data/fonts/droid/DroidSans.ttf", mainFontHeight);

        dictionary["mSandbox"] = "Sandbox";
        dictionary["mNewGame"] = "New game";
        dictionary["mResumeGame"] = "Resume game";
        dictionary["mLoadGame"] = "Load game";
        dictionary["mOptions"] = "Options";
        dictionary["mExit"] = "Exit";
        readLocalization(dictionary, "data/locale/ru.txt");
    }

    void goToRoom(string roomName, bool free = true, bool load = true)
    {
        nextRoom = roomName;
        freeCurrent = free;
        loadNext = load;
    }

    void update()
    {
        if (nextRoom.length)
        {
            if (currentRoom !is null)
            {
                currentRoom.freeEvents();
                if (freeCurrent)
                {
                    currentRoom.freeObjects();
                }
            }

            if (!(nextRoom in rooms))
                throw new Exception("No such room: " ~ nextRoom);

            previousRoom = currentRoom;
            currentRoom = rooms[nextRoom];
            nextRoom = "";
            rooms["_current_room_"] = currentRoom;

            if (loadNext)
            {
                currentRoom.load();
            }

            currentRoom.createEvents();
        }

        if (currentRoom !is null)
            currentRoom.draw();
    }
}

class GameObject
{
    AppManager manager;
    GameLogicManager logic;
    int keyDownActionId;
    int keyUpActionId;
    int mouseButtonDownActionId;
    int mouseButtonUpActionId;

    this(GameLogicManager logi)
    {
        logic = logi;
        manager = logi.appManager;
    }

    void createEvents()
    {
        keyDownActionId = manager.bindActionToEvent(EventType.KeyDown, &onKeyDown);
        keyUpActionId = manager.bindActionToEvent(EventType.KeyUp, &onKeyUp);
        mouseButtonDownActionId = manager.bindActionToEvent(EventType.MouseButtonDown, &onMouseButtonDown);
        mouseButtonUpActionId = manager.bindActionToEvent(EventType.MouseButtonUp, &onMouseButtonUp);
    }

    void free()
    {
        onFree();
    }

    void freeEvents()
    {
        manager.unbindActionFromEvent(EventType.KeyDown, keyDownActionId);
        manager.unbindActionFromEvent(EventType.KeyUp, keyUpActionId);
        manager.unbindActionFromEvent(EventType.MouseButtonDown, mouseButtonDownActionId);
        manager.unbindActionFromEvent(EventType.MouseButtonUp, mouseButtonUpActionId);
    }

    void draw()
    {
        onDraw(manager.deltaTime);
    }

    // Override these:
    void onDraw(double delta) {}
    void onKeyDown() {}
    void onKeyUp() {}
    void onMouseButtonDown() {}
    void onMouseButtonUp() {}
    void onFree() {}
}

class GameRoom
{
    string name;
    GameLogicManager logic;
    GameObject[] objects;

    this(string roomName, GameLogicManager logi)
    {
        name = roomName;
        logic = logi;
    }

    void createEvents()
    {
        foreach(obj; objects)
            obj.createEvents();
    }

    void addObject(GameObject obj)
    {
        objects ~= obj;
    }

    void draw()
    {
        foreach(obj; objects)
            obj.draw();
    }

    void freeEvents()
    {
        foreach(obj; objects)
            if (obj !is null) 
                obj.freeEvents();
    }

    void freeObjects()
    {
        foreach(obj; objects)
            if (obj !is null) 
                obj.free();
        objects = [];
    }

    void load()
    {
        onLoad();
    }

    void onLoad() {}
}

class ExitRoom: GameRoom
{
    this(string roomName, GameLogicManager logi)
    {
        super(roomName, logi);
    }

    override void onLoad()
    {
        logic.appManager.running = false;
    }
}

