/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module atrium.graphics.material;

private
{
    import derelict.opengl.gl;
    import derelict.opengl.glext;
	
    import dlib.image.color;
	
    import atrium.core.modifier;
    import atrium.graphics.texture;
    import atrium.graphics.shader;
}

enum TextureCombinerMode: ushort
{
    Blend = 0,
    Modulate = 1,
    Add = 2,
    Subtract = 3,
    Dot3 = 4,
    Dot3Alpha = 5
}

class Material: Modifier
{
    ColorRGBAf ambientColor;
    ColorRGBAf diffuseColor;
    ColorRGBAf specularColor;
    ColorRGBAf emissionColor;
    float shininess;
    Shader shader;
    Texture[8] textures;
    ushort[8] texBlendMode = 0;
    bool shadeless = false;

    this()
    {
        ambientColor = ColorRGBAf(0.2f, 0.2f, 0.2f, 1.0f);
        diffuseColor = ColorRGBAf(0.8f, 0.8f, 0.8f, 1.0f);
        specularColor = ColorRGBAf(1.0f, 1.0f, 1.0f, 1.0f);
        emissionColor = ColorRGBAf(0.0f, 0.0f, 0.0f, 1.0f);
        shininess = 64.0f;
    }

    void bind(double delta)
    {
        if (shadeless)
        {            glDisable(GL_LIGHTING);
            glColor4fv(diffuseColor.arrayof.ptr);
        }
        else
        {    
            glMaterialfv(GL_FRONT_AND_BACK, GL_AMBIENT, ambientColor.arrayof.ptr);
            glMaterialfv(GL_FRONT_AND_BACK, GL_DIFFUSE, diffuseColor.arrayof.ptr);
            glMaterialfv(GL_FRONT_AND_BACK, GL_SPECULAR, specularColor.arrayof.ptr);
            glMaterialfv(GL_FRONT_AND_BACK, GL_EMISSION, emissionColor.arrayof.ptr);
            glMaterialfv(GL_FRONT_AND_BACK, GL_SHININESS, &shininess);
        }

        glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);

        // TODO:
        // Select BlendMode
        //    Case T_Normal
        //        glTexEnvf (GL_TEXTURE_ENV, GL_COMBINE_RGB,GL_REPLACE)
        //    Case T_Blend
        //        glTexEnvf(GL_TEXTURE_ENV,GL_COMBINE_RGB,GL_BLEND)
        //    Case T_modulated
        //        glTexEnvf(GL_TEXTURE_ENV,GL_COMBINE_RGB,GL_MODULATE)
        //    Case T_Add
        //        glTexEnvf (GL_TEXTURE_ENV, GL_COMBINE_RGB,GL_ADD) 
        //    Case T_Dot3
        //        glTexEnvf (GL_TEXTURE_ENV, GL_COMBINE_RGB,GL_DOT3_RGB)
        //    Case T_Dot3Alpha
        //        glTexEnvf (GL_TEXTURE_ENV, GL_COMBINE_RGB,GL_DOT3_RGBA)
        //    Case T_Subtract
        //        glTexEnvf(GL_TEXTURE_ENV,GL_COMBINE_RGB,GL_SUBTRACT)

        foreach(i, tex; textures)
        {
            if (tex !is null)
            {
                glActiveTextureARB(GL_TEXTURE0_ARB + i);
                if (texBlendMode[i] == TextureCombinerMode.Modulate)
                {
                    glTexEnvf(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_MODULATE);
                }
                else
                {
                    glTexEnvf(GL_TEXTURE_ENV, GL_COMBINE_RGB, GL_BLEND);
                }
                tex.bind(delta);
            }
        }

        if (shader)
            shader.bind(delta);
    }

    void unbind()
    {
        if (shader)
            shader.unbind();

        foreach(i, tex; textures)
        {
            if (tex !is null)
            {
                glActiveTextureARB(GL_TEXTURE0_ARB + i);
                tex.unbind();
            }
        }

        glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);

        glActiveTextureARB(GL_TEXTURE0_ARB);
		
        if (shadeless)
            glEnable(GL_LIGHTING);
    }

    void free()
    {
    }
}
