/*
Copyright (c) 2016 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.asset.entity;

import std.conv;
import dlib.core.memory;
import dlib.container.dict;
import dlib.math.vector;
import dlib.math.quaternion;
import dlib.image.color;
import dgl.graphics.entity;
import dgl.graphics.light;

enum PropType
{
    Undefined,
    Int,
    Float,
    Vec2f,
    Vec3f,
    Vec4f,
    String
}

struct Property
{
    PropType type = PropType.Undefined;

    this(int v)
    {
        type = PropType.Int;
        asInt = v;
    }

    this(float v)
    {
        type = PropType.Float;
        asFloat = v;
    }

    this(Vector2f v)
    {
        type = PropType.Vec2f;
        asVector2f = v;
    }

    this(Vector3f v)
    {
        type = PropType.Vec3f;
        asVector3f = v;
    }

    this(Vector4f v)
    {
        type = PropType.Vec4f;
        asVector4f = v;
    }

    this(string v)
    {
        type = PropType.String;
        asString = v;
    }

    union
    {
        int asInt;
        float asFloat;
        Vector2f asVector2f;
        Vector3f asVector3f;
        Vector4f asVector4f;
        string asString;
    }

    string toString()
    {
        if (type == PropType.Int)
            return to!string(asInt);
        else if (type == PropType.Float)
            return to!string(asFloat);
        else if (type == PropType.Vec2f)
            return asVector2f.toString;
        else if (type == PropType.Vec3f)
            return asVector3f.toString;
        else if (type == PropType.Vec4f)
            return asVector4f.toString;
        else if (type == PropType.String)
            return asString;
        else
            return "Undefined";
    }

    void free()
    {
        if (type == PropType.String)
        {
            if (asString.length)
                Delete(asString);
        }
    }
}

class DGL3Entity: Entity
{
    string name;
    Dict!(Property, string) props;

    this()
    {
        super();
        props = dict!(Property, string);
    }

    ~this()
    {
        foreach(k, v; props)
        {
            v.free();
            Delete(k);
        }
        Delete(props);
        if (name.length)
            Delete(name);
    }
}

class DGL3Light: Light
{
    int id;
    string name;

    this()
    {        
        super();
    }

    ~this()
    {
        if (name.length)
            Delete(name);
    }
}
