/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module engine.physics.rigidbody;

import std.math;

import dlib.math.vector;
import dlib.math.quaternion;
import dlib.math.matrix4x4;
import dlib.math.matrix3x3;

import engine.physics.geometry;
import engine.physics.contact;

enum BodyType
{
    Static,
    Dynamic,
    Kinematic
}

class RigidBody
{
    BodyType type = BodyType.Dynamic;
    
    Vector3f position;
    Vector3f linearVelocity;

    Quaternionf orientation;
    Vector3f angularVelocity;

    float mass = 1.0f;
    float inertiaMoment = 1.0f;
    
    float invMass = 1.0f;
    float invInertiaMoment = 1.0f;
    
    float dampingFactor = 0.999f;

    Vector3f forceAccumulator;
    Vector3f torqueAccumulator;

    Geometry geometry;
    
    bool disableRotation = false;
    bool disableGravity = false;
    
    Vector3f gravityDirection;
    Contact lastGroundContact;

    bool onGround = false;
    
    this(Vector3f pos = Vector3f(0.0f, 0.0f, 0.0f))
    {
        position = pos;
        linearVelocity = Vector3f(0.0f, 0.0f, 0.0f);

        orientation = Quaternionf(0.0f, 0.0f, 0.0f, 1.0f);
        angularVelocity = Vector3f(0.0f, 0.0f, 0.0f);

        forceAccumulator = Vector3f(0.0f, 0.0f, 0.0f);
        torqueAccumulator = Vector3f(0.0f, 0.0f, 0.0f);
    }
    
    void setGeometry(Geometry geom)
    {
        geometry = geom;
        setMass(mass);
    }
    
    void setMass(float m)
    {
        mass = m;       
        invMass = 1.0f / mass;
        
        if (geometry !is null)
        {
            inertiaMoment = geometry.inertiaMoment(mass);
            invInertiaMoment = 1.0f / inertiaMoment;
        }
    }
    
    void integrate(double delta)
    {
        if (type == BodyType.Dynamic)
        {
            Vector3f acceleration;

            acceleration = forceAccumulator * invMass;
            linearVelocity += acceleration * delta;

            acceleration = torqueAccumulator * invInertiaMoment;
            angularVelocity += acceleration * delta;
            
            linearVelocity *= dampingFactor;
            angularVelocity *= dampingFactor;
            //linearVelocity *= pow(dampingFactor, delta);
            //angularVelocity *= pow(dampingFactor, delta);
            
            position += linearVelocity * delta;
            
            orientation += 0.5f * Quaternionf(angularVelocity, 0.0f) * orientation * delta;
            orientation.normalize();
        }
    }
       
    void updateGeomTransformation()
    {
        if (geometry !is null)
        {
            if (disableRotation)
                geometry.setTransformation(position, Quaternionf(0.0f, 0.0f, 0.0f, 1.0f));
            else
                geometry.setTransformation(position, orientation);
        }
    }
    
    void resetForces()
    {
        forceAccumulator = Vector3f(0.0f, 0.0f, 0.0f);
        torqueAccumulator = Vector3f(0.0f, 0.0f, 0.0f);
    }
    
    void applyForce(Vector3f force)
    {
        forceAccumulator += force;
    }
    
    void applyTorque(Vector3f torque)
    {
        if (!disableRotation)
            torqueAccumulator += torque;
    }
    
    void applyForceAtPoint(Vector3f force, Vector3f point)
    {
        forceAccumulator += force;
        if (!disableRotation)
            torqueAccumulator += cross(point - position, force);
    }
    
    void applyForceAtLocalPoint(Vector3f force, Vector3f point)
    {
        forceAccumulator += force;
        if (!disableRotation)
            torqueAccumulator += cross(point, force);
    }
    
    void applyImpulse(Vector3f impulse)
    {
        linearVelocity += impulse * invMass;
    }
    
    void applyAngularImpulse(Vector3f angularImpulse)
    {
        if (!disableRotation)
            angularVelocity += angularImpulse * invInertiaMoment;
    }
    
    void applyImpulseAtPoint(Vector3f impulse, Vector3f point)
    {
        linearVelocity += impulse * invMass;
        
        if (!disableRotation)
        {
            Vector3f angularImpulse = cross(point - position, impulse);
            angularVelocity += angularImpulse * invInertiaMoment;
        }
    }
    
    void applyImpulseAtLocalPoint(Vector3f impulse, Vector3f point)
    {
        linearVelocity += impulse * invMass;
        
        if (!disableRotation)
        {
            Vector3f angularImpulse = cross(point, impulse);
            angularVelocity += angularImpulse * invInertiaMoment;
        }
    }
    
    bool isStatic()
    {
        return (type == BodyType.Static);
    }
}

