/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module engine.core.application;

private
{
    import std.stdio;
    import std.conv;
    import std.string;
    import std.process;

    import derelict.util.compat;
    import derelict.sdl.sdl;
    import derelict.opengl.gl;
    import derelict.opengl.glu;
    import derelict.opengl.glext;
    import derelict.freetype.ft;
    import derelict.openal.al;
    import derelict.ogg.ogg;
    import derelict.ogg.vorbis;
    import derelict.ogg.vorbisfile;
    
    import engine.multimedia.oggplayer;
}

public
{ 
    import engine.core.appmanager;
}

class Application
{
    private:

    int _priv_quitActionId, _priv_resizeActionId;

    protected:

    uint videoWidth, videoHeight;
    AppManager manager;
    bool soundEnabled = true;
    
    ALCdevice* device;
    ALCcontext* context;

    version(Windows)
    {
        enum sharedLibSDL = "SDL.dll";
        enum sharedLibFT = "freetype.dll";
        enum sharedLibAL = "OpenAL32.dll";
        enum sharedLibOgg = "libogg.dll";
        enum sharedLibVorbis = "libvorbis.dll";
        enum sharedLibVorbisFile = "libvorbisfile.dll";
    }
    version(linux)
    {
        enum sharedLibSDL = "./libsdl.so";
        enum sharedLibFT = "./libfreetype.so";
        enum sharedLibAL = "./libopenal.so";
        enum sharedLibOgg = "./libogg.so";
        enum sharedLibVorbis = "./libvorbis.so";
        enum sharedLibVorbisFile = "./libvorbisfile.so";
    }

    public:

    this(uint w, uint h, string caption, GLVersion glver = GLVersion.GL12)
    {
        videoWidth = w;
        videoHeight = h;

        DerelictGL.load();
        DerelictGLU.load();
        DerelictSDL.load(sharedLibSDL);
        DerelictFT.load(sharedLibFT);
        DerelictAL.load(sharedLibAL);
        DerelictOgg.load(sharedLibOgg);
        DerelictVorbis.load(sharedLibVorbis);
        DerelictVorbisFile.load(sharedLibVorbisFile);

        if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_JOYSTICK) < 0)
            throw new Exception("Failed to init SDL: " ~ to!string(SDL_GetError()));

        SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
        SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 5);
        SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 5);
        SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 5);
        SDL_GL_SetAttribute(SDL_GL_BUFFER_SIZE, 32);
        SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 16);

        environment["SDL_VIDEO_WINDOW_POS"] = "";
        environment["SDL_VIDEO_CENTERED"] = "1";

        auto screen = SDL_SetVideoMode(videoWidth, videoHeight, 0, SDL_OPENGL | SDL_RESIZABLE);
        if (screen is null)
            throw new Exception("Failed to set video mode: " ~ to!string(SDL_GetError()));

        SDL_WM_SetCaption(toStringz(caption), null);
        SDL_ShowCursor(1);

        DerelictGL.loadClassicVersions(glver); 
        DerelictGL.loadExtensions();

        glViewport(0, 0, videoWidth, videoHeight);
        float aspectRatio = cast(float)videoWidth / cast(float)videoHeight;
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        gluPerspective(60, aspectRatio, 0.01, 800.0);
        glMatrixMode(GL_MODELVIEW);

        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glEnable(GL_BLEND);
        glEnable(GL_NORMALIZE);
        glShadeModel(GL_SMOOTH);
        glAlphaFunc(GL_GREATER, 0.0);
        glEnable(GL_ALPHA_TEST);
        glEnable(GL_DEPTH_TEST);
        glDepthFunc(GL_LESS);
        glEnable(GL_CULL_FACE);

        manager = new AppManager(videoWidth, videoHeight);

        int _priv_quitActionId = manager.bindActionToEvent(EventType.Quit, &onQuit);
        int _priv_resizeActionId = manager.bindActionToEvent(EventType.Resize, &onResize);
        
        if (soundEnabled)
        {
            ALCchar* defaultDevice = cast(ALCchar*)alcGetString(null, 
                ALC_DEFAULT_DEVICE_SPECIFIER);
            device = alcOpenDevice(defaultDevice);
            assert(device !is null, "Failed to open audio device");
            writefln("OpenAL device: %s", to!string(defaultDevice));
            context = alcCreateContext(device, null);
            alcMakeContextCurrent(context);
            alcProcessContext(context);
        }
    }

    private:

    void onQuit()
    {
        manager.running = false;
    }

    void onResize()
    {
        SDL_Surface* screen = SDL_SetVideoMode(manager.window_width, 
                                               manager.window_height, 
                                               0, SDL_OPENGL | SDL_RESIZABLE);
        if (screen is null)
            throw new Exception("failed to set video mode: " ~ to!string(SDL_GetError()));

        glViewport(0, 0, manager.window_width, manager.window_height);
        float aspectRatio = cast(float)manager.window_width / cast(float)manager.window_height;
        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        gluPerspective(60, aspectRatio, 0.1, 400.0);
        glMatrixMode(GL_MODELVIEW);
    }

    protected:

    void onUpdate()
    {
    }

    public:

    void run()
    {
        while (manager.running)
        {
            manager.update();

            onUpdate();

            SDL_GL_SwapBuffers();
            SDL_Delay(1);
        }

        manager.unbindActionFromEvent(EventType.Resize, _priv_resizeActionId);
        manager.unbindActionFromEvent(EventType.Quit, _priv_quitActionId);
    
        manager.free();
        
        auto ovplayer = OVPlayer();
        ovplayer.stop();
        
        if (soundEnabled)
        {
            alcMakeContextCurrent(null);
            alcDestroyContext(context);
            alcCloseDevice(device);
        }

        SDL_Quit();
    }
}

