/*
Copyright (c) 2015 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.ui.textlineinput;

import std.stdio;

import dlib.core.memory;
import dlib.math.vector;
import dlib.image.color;

import dgl.core.interfaces;
import dgl.core.event;
import dgl.ui.font;
import dgl.ui.textline;

class TextLineInput: TextListener, Drawable
{
    TextLine textLine;
    TextLine cursor;
    bool alignToWindow = true;
    int oldWindowHeight;

    this(EventManager emngr, Font font, Vector2f pos)
    {
        super(emngr);

        textLine = New!TextLine(font, "", pos);
        textLine.alignment = Alignment.Left;
        textLine.color = Color4f(1, 1, 1);

        cursor = New!TextLine(font, "_", pos);
        cursor.alignment = Alignment.Left;
        cursor.color = Color4f(1, 1, 1);

        oldWindowHeight = emngr.windowHeight;
    }

    override void onKeyDown(int key)
    {
        super.onKeyDown(key);

        textLine.setText(toString);
        cursor.setPosition(textLine.textWidth + cursor.textWidth, cursor.position.y);
    }

    float timer = 0.0f;
    bool cursorState = true;

    override void draw(double dt)
    {
        processEvents();

        textLine.draw(dt);

        timer += dt;
        if (timer >= 0.5f)
        {
            cursorState = !cursorState;
            timer = 0.0f;
        }

        if (cursorState)
            cursor.draw(dt);
    }

    ~this()
    {
        //writeln("Deleting TextLineInput...");
        textLine.free();
        cursor.free();
    }

    override void free()
    {
        Delete(this);
    }

    override void onResize(int width, int height)
    {
        if (alignToWindow)
        {
            float y = cast(float)oldWindowHeight - textLine.position.y;
            textLine.position.y = height - y;
            cursor.position.y = height - y;
            oldWindowHeight = height;
        }
    }
}
