/*
Copyright (c) 2024-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module audio;

import dlib.core.memory;
import dlib.container.array;
import dlib.container.dict;
import dlib.text.str;
import dlib.math.vector;
import soloud;

__gshared
{
    Soloud audio;
    Array!String filenames;
    Dict!(WavStream, string) music;
    Dict!(Wav, string) sounds;
    int musicVoice;
    float soundEffectsVolume = 0.5f;
    float musicVolume = 0.5f;
}

void initSound()
{
    audio = audio.create();
    audio.init(audio.CLIP_ROUNDOFF | audio.LEFT_HANDED_3D);
    
    music = dict!(WavStream, string);
    sounds = dict!(Wav, string);
    
    setSoundEffectsVolume(0.5f);
    setMusicVolume(0.5f);
}

void releaseSound()
{
    Delete(music);
    Delete(sounds);
    
    audio.deinit();
    audio.free();
    
    foreach(f; filenames)
        f.free();
    filenames.free();
}

void playSound(string filename, bool checkPlaying = false)
{
    if ((filename in sounds) is null)
    {
        String filenameStr = String(filename);
        auto sound = Wav.create();
        sound.load(filenameStr.ptr);
        sounds[filenameStr] = sound;
        filenames.append(filenameStr);
    }
    
    Wav sound = sounds[filename];
    
    if (checkPlaying == false || audio.countAudioSource(sound) == 0)
    {
        int soundVoice = audio.play(sound);
        audio.setVolume(soundVoice, soundEffectsVolume);
    }
}

void setSoundEffectsVolume(float vol)
{
    soundEffectsVolume = vol;
}

void playMusic(string filename, bool looping = true)
{
    if ((filename in music) is null)
    {
        String filenameStr = String(filename);
        auto track = WavStream.create();
        track.load(filenameStr.ptr);
        music[filenameStr] = track;
        filenames.append(filenameStr);
    }
    
    musicVoice = audio.play(music[filename]);
    audio.setLooping(musicVoice, looping);
    audio.setVolume(musicVoice, musicVolume);
}

bool musicIsPlaying()
{
    return cast(bool)audio.isValidVoiceHandle(musicVoice);
}

void stopMusic()
{
    audio.stop(musicVoice);
}

void setMusicVolume(float vol)
{
    musicVolume = vol;
    audio.setVolume(musicVoice, vol);
}

void setListener(Vector3f cameraPosition, Vector3f cameraDirection, Vector3f cameraUp)
{
    audio.set3dListenerPosition(cameraPosition.x, cameraPosition.y, cameraPosition.z);
    audio.set3dListenerAt(cameraDirection.x, cameraDirection.y, cameraDirection.z);
    audio.set3dListenerUp(cameraUp.x, cameraUp.y, cameraUp.z);
    audio.update3dAudio();
}
