/*
Copyright (c) 2024-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module gameapp;

import std.stdio;
import std.conv;
import dagon;
import dagon.ext.newton;
import dagon.ext.imgui;
import soloud;
import scenes.mainmenu;
import scenes.game;
import audio;
import ui;
import client;

class GameApp: Game
{
    StdFileSystem fs;
    UI ui;
    
    Dict!(Trophy, TrophyId) trophies;
    
    this(uint w, uint h, bool fullscreen, string title, string[] args)
    {
        super(w, h, fullscreen, title, args);
        
        fs = New!StdFileSystem();
        
        trophies = dict!(Trophy, TrophyId);
        addTrophy(TrophyId.SuccessfulLanding);
        
        auto mainMenuScene = New!MainMenuScene(this);
        scenes["MainMenu"] = mainMenuScene;
        currentScene = mainMenuScene;
        
        ui = New!UI(this, mainMenuScene, args);
        eventManager.onProcessEvent = &ui.onProcessEvent;
    }
    
    ~this()
    {
        Delete(fs);
        Delete(trophies);
    }
    
    Trophy addTrophy(TrophyId id)
    {
        Trophy trophy = New!Trophy(id, this);
        trophies[id] = trophy;
        return trophy;
    }
    
    override void onUpdate(Time t)
    {
        super.onUpdate(t);
        ui.update(t);
    }
    
    override void onRender()
    {
        super.onRender();
        if (ui.visible)
        {
            ui.render();
        }
    }
    
    override void setCurrentScene(Scene scene, bool releaseCurrent = false)
    {
        super.setCurrentScene(scene, releaseCurrent);
    }
    
    override void setCurrentScene(string name, bool releaseCurrent = false)
    {
        super.setCurrentScene(name, releaseCurrent);
        
        if (name == "MainMenu")
        {
            ui.visible = true;
        }
        
        currentScene.focused = true;
    }
    
    override void exit()
    {
        stopMusic();
        super.exit();
    }
}
