/*
Copyright (c) 2024-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module loading;

import dagon;

class GameLoadingScreen: EventListener
{
    Application app;
    ShapeQuad shapeQuad;
    Entity eBackground;
    Entity ePreloader;
    Entity ePreloaderPivot;
    HUDShader hudShader;
    float backgroundAspectRatio;
    float loadingScreenShowDelay = 0.25f;
    double loadingTime = 0.0;
    
    this(string filename, Application app, Scene scene)
    {
        super(app.eventManager, scene);
        this.app = app;
        TextureAsset preloaderTextureAsset = scene.addTextureAsset("assets/ui/preloader.png", true);
        TextureAsset loadingTextureAsset = scene.addTextureAsset(filename, true);
        backgroundAspectRatio = cast(float)loadingTextureAsset.texture.width / cast(float)loadingTextureAsset.texture.height;
        shapeQuad = New!ShapeQuad(this);
        hudShader = New!HUDShader(this);
        
        eBackground = New!Entity(this);
        eBackground.drawable = shapeQuad;
        eBackground.material = New!Material(this);
        eBackground.material.baseColorTexture = loadingTextureAsset.texture;
        eBackground.material.useCulling = false;
        eBackground.material.blendMode = Transparent;
        eBackground.material.opacity = 0.0f;
        resizeBackground(eventManager.windowWidth, eventManager.windowHeight);
        
        ePreloaderPivot = New!Entity(this);
        ePreloader = New!Entity(this);
        ePreloader.setParent(ePreloaderPivot);
        ePreloader.drawable = shapeQuad;
        ePreloader.material = New!Material(this);
        ePreloader.material.baseColorTexture = preloaderTextureAsset.texture;
        ePreloader.material.useCulling = false;
        ePreloader.material.blendMode = Additive;
        ePreloader.material.opacity = 0.0f;
        resizePreloader(eventManager.windowWidth, eventManager.windowHeight);
    }
    
    void resizeBackground(int width, int height)
    {
        float aspectRatio = cast(float)width / cast(float)height;
        
        if (aspectRatio > backgroundAspectRatio)
            eBackground.scaling = Vector3f(width, width / backgroundAspectRatio, 1.0f);
        else
            eBackground.scaling = Vector3f(height * backgroundAspectRatio, height, 1.0f);
        
        eBackground.position = Vector3f(
            cast(float)width * 0.5 - eBackground.scaling.x * 0.5,
            cast(float)height * 0.5 - eBackground.scaling.y * 0.5,
            0.0f
        );
    }
    
    void resizePreloader(int width, int height)
    {
        float size = cast(float)height * 0.2f;
        ePreloader.scaling = Vector3f(size, size, 1.0f);
        ePreloaderPivot.position = Vector3f(
            cast(float)width * 0.5,
            cast(float)height * 0.8,
            0.0f
        );
        ePreloader.position = Vector3f(
            -ePreloader.scaling.x * 0.5,
            -ePreloader.scaling.y * 0.5,
            0.0f);
    }
    
    void update(Time t, float progress)
    {
        processEvents(false);
        
        loadingTime += t.delta;
        
        if (loadingTime > loadingScreenShowDelay)
        {
            if (eBackground.material.opacity < 1.0f)
                eBackground.material.opacity += 2.0f * t.delta;
            
            if (ePreloader.material.opacity < 1.0f)
                ePreloader.material.opacity += 2.0f * t.delta;
            
            ePreloaderPivot.roll(90.0f * t.delta);
        }
        
        eBackground.update(t);
        ePreloaderPivot.update(t);
        ePreloader.update(t);
    }
    
    void render()
    {
        GraphicsState state;
        state.reset();
        state.modelViewMatrix = eBackground.absoluteTransformation;
        state.projectionMatrix = orthoMatrix(0.0f, eventManager.windowWidth, eventManager.windowHeight, 0.0f, 0.0f, 1000.0f);
        state.invProjectionMatrix = state.projectionMatrix.inverse;
        state.resolution = Vector2f(eventManager.windowWidth, eventManager.windowHeight);
        state.zNear = 0.0f;
        state.zFar = 1000.0f;

        glScissor(0, 0, eventManager.windowWidth, eventManager.windowHeight);
        glViewport(0, 0, eventManager.windowWidth, eventManager.windowHeight);

        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

        if (loadingTime < loadingScreenShowDelay) return;

        drawEntity(&state, eBackground);
        drawEntity(&state, ePreloader);
    }
    
    void drawEntity(GraphicsState* state, Entity entity)
    {
        state.modelViewMatrix = state.viewMatrix * entity.absoluteTransformation;
        state.normalMatrix = state.modelViewMatrix.inverse.transposed;
        state.shader = hudShader;

        if (entity.material)
            entity.material.bind(state);

        hudShader.bind();
        hudShader.bindParameters(state);

        if (entity.drawable)
            entity.drawable.render(state);

        hudShader.unbindParameters(state);
        hudShader.unbind();

        if (entity.material)
            entity.material.unbind(state);
    }
    
    override void onResize(int width, int height)
    {
        if (eBackground) resizeBackground(width, height);
        if (ePreloader) resizePreloader(width, height);
    }
}
