/*
Copyright (c) 2013 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module atrium.physics.geometry;

private
{
    import dlib.math.vector;
    import dlib.geometry.sphere;
    import dlib.geometry.plane;
    import dlib.geometry.triangle;
}

enum GeometryType
{
    Plane,
    Sphere,
    Triangle,
    //SpaceHierarchy
}

abstract class Geometry
{
    GeometryType type;
    float inertiaMoment(float mass);
    void setCenter(Vector3f pos);
}

final class GeomSphere: Geometry
{
    Sphere sphere;
    alias sphere this;
    
    this(float newRadius, Vector3f newCenter = Vector3f(0.0f, 0.0f, 0.0f))
    {
        sphere.center = newCenter;
        sphere.radius = newRadius;
        type = GeometryType.Sphere;
    }
    
    override float inertiaMoment(float mass)
    {
        return mass * sphere.radius * sphere.radius * 2.0f / 5.0f;
    }
    
    override void setCenter(Vector3f pos)
    {
        sphere.center = pos;
    }
}

final class GeomPlane: Geometry
{
    Plane plane;
    alias plane this;
    
    this(Vector3f p, Vector3f n)
    {
        plane.fromPointAndNormal(p, n);
        type = GeometryType.Plane;
    }
    
    override float inertiaMoment(float mass)
    {
        return float.max; // infinite mass
    }
    
    override void setCenter(Vector3f pos)
    {
        plane.fromPointAndNormal(pos, plane.normal);
    }
}

final class GeomTriangle: Geometry
{
    Triangle tri;
    alias tri this;

    this(Triangle newTri)
    {
        tri = newTri;
        type = GeometryType.Triangle;
    }

    override float inertiaMoment(float mass)
    {
        return float.max; // infinite mass
    }
    
    override void setCenter(Vector3f pos)
    {
    }
}

/*
final class GeomSpaceHierarchy: Geometry
{
    BVHNode root;

    this(BVHNode rootNode)
    {
        root = rootNode;
        type = GeometryType.SpaceHierarchy;
    }

    override float inertiaMoment(float mass)
    {
        return float.max; // infinite mass
    }
    
    override void setCenter(Vector3f pos)
    {
    }
}
*/

