/*
Copyright (c) 2016 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.graphics.rtt;

import dlib.core.memory;
import dlib.math.vector;
import dlib.math.affine;
import dgl.core.api;
import dgl.core.event;
import dgl.graphics.scene;
import dgl.graphics.pass;
import dgl.graphics.material;
import dgl.graphics.texture;

class DepthTexture: Texture
{
    this(uint w, uint h)
    {
        scroll = Vector2f(0, 0);

        width = w;
        height = h;
        
        glGenTextures(1, &tex);
        glBindTexture(GL_TEXTURE_2D, tex);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
        glTexImage2D(GL_TEXTURE_2D, 0,
           GL_DEPTH_COMPONENT, w, h, 0,
           GL_DEPTH_COMPONENT, GL_UNSIGNED_BYTE, null);
        glBindTexture(GL_TEXTURE_2D, 0);
    }
}

/*
 * Render to texture using FBO
 */
class RTTPass: Pass
{
    GLuint fbo;
    GLuint rbDepth;
    Texture texture;
    DepthTexture depthTexture;
    bool type3d;

    // type2d: true - 3D pass, false - 2D pass
    this(uint w, uint h, bool type3d, Scene s, EventManager emngr)
    {
        super(0, 0, w, h, s, emngr);
        
        this.type3d = type3d;
        
        clear = true;
        alignToWindow = false;
        
        if (type3d)
        {
            aspectRatio = cast(float)(eventManager.windowWidth) / cast(float)(eventManager.windowHeight);
            projectionMatrix = perspectiveMatrix(60.0f, aspectRatio, 0.1f, 100.0f);
        }
        else
        {
            projectionMatrix = orthoMatrix(0.0f, w, 0.0f, h, 0.0f, 1.0f);
        }
        
        texture = New!Texture(w, h);
        depthTexture = New!DepthTexture(w, h);

        // Create the FBO
        glGenFramebuffers(1, &fbo);        
        glBindFramebuffer(GL_FRAMEBUFFER, fbo);  
        
        //glGenRenderbuffers(1, &rbDepth);
        //glBindRenderbuffer(GL_RENDERBUFFER, rbDepth);
        //glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT, w, h);
        //glBindRenderbuffer(GL_RENDERBUFFER, 0);
        
        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, texture.tex, 0); 
        //glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, rbDepth);
        
        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, depthTexture.tex, 0);
        
        GLenum fboStatus = glCheckFramebufferStatus(GL_FRAMEBUFFER);       
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
    }
    
    override void onResize(int width, int height)
    {
        if (type3d)
        {
            aspectRatio = cast(float)(width) / cast(float)(height);
            projectionMatrix = perspectiveMatrix(60.0f, aspectRatio, 0.1f, 100.0f);
        }
    }
    
    static bool supported()
    {
        return DerelictGL.isExtensionSupported("GL_ARB_framebuffer_object");
    }
    
    ~this()
    {
        //glDeleteRenderbuffers(1, &rbDepth);
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        glDeleteFramebuffers(1, &fbo);
        Delete(texture);
        Delete(depthTexture);
    }
    
    override void draw(double dt)
    {        
        glBindFramebuffer(GL_FRAMEBUFFER, fbo);
        super.draw(dt);
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
    }
}
