/*
Copyright (c) 2015-2016 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module dgl.graphics.shadow;

import std.math;
import dlib.core.memory;
import dlib.math.vector;
import dlib.math.matrix;
import dlib.math.transformation;
import dlib.math.quaternion;
import dlib.math.utils;
import dlib.image.color;
import dgl.core.api;
import dgl.core.application;
import dgl.core.event;
import dgl.graphics.pass;
import dgl.graphics.scene;
import dgl.graphics.material;

/*
 * Shadow map implementation.
 * Uses FBO and depth buffer
 */

class ShadowMapPass: Pass3D
{
    protected:
    GLuint depthBuffer;
    GLuint fbo;
    float projSize;   
    Material mat;
    
    public:
    Vector3f lightPosition;
    Quaternionf lightRotation;
    
    public:
    this(uint res, Scene castScene, uint group, EventManager emngr)
    {
        super(0, 0, res, res, castScene, emngr);
        alignToWindow = false;
        shadeless = true;
        groupID = group;
        mat = New!Material();
        defaultMaterial = mat;
        clear = true;
        
        glGenTextures(1, &depthBuffer);
        glBindTexture(GL_TEXTURE_2D, depthBuffer);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
        
        Color4f col = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        glTexParameterfv(GL_TEXTURE_2D, GL_TEXTURE_BORDER_COLOR, col.arrayof.ptr);

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_COMPARE_MODE, GL_COMPARE_R_TO_TEXTURE);
	    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_COMPARE_FUNC, GL_LEQUAL);
	    glTexParameteri(GL_TEXTURE_2D, GL_DEPTH_TEXTURE_MODE, GL_INTENSITY);

        glTexImage2D(GL_TEXTURE_2D, 0,
           GL_DEPTH_COMPONENT, viewWidth, viewHeight, 0,
           GL_DEPTH_COMPONENT, GL_UNSIGNED_BYTE, null);
           
        glBindTexture(GL_TEXTURE_2D, 0);
        
        glGenFramebuffers(1, &fbo);
	    glBindFramebuffer(GL_FRAMEBUFFER, fbo);
        
        glDrawBuffer(GL_NONE);
	    glReadBuffer(GL_NONE);
        
        glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D, depthBuffer, 0);
        
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        
        projSize = 10;
        projectionMatrix = orthoMatrix(-projSize, projSize, -projSize, projSize, -1.0f, 100.0f);
        
        lightPosition = Vector3f(0.0f, 0.0f, 0.0f);
        lightRotation = rotationQuaternion(0, degtorad(-90.0f));
    }
    
    @property
    {
        float projectionSize()
        {
            return projectionSize;
        }
    
        void projectionSize(float size)
        {
            projSize = size;
            projectionMatrix = orthoMatrix(-projSize, projSize, -projSize, projSize, -20.0f, 100.0f);
        }
    }
    
    static bool supported()
    {
        return Material.isGLSLSupported() && DerelictGL.isExtensionSupported("GL_ARB_framebuffer_object");
    }
    
    void update(double dt)
    {
        modelViewMatrix = 
            lightRotation.conj.toMatrix4x4 * 
            translationMatrix(-lightPosition);
    }

    override void draw(double dt)
    {        
        glBindFramebuffer(GL_FRAMEBUFFER, fbo);
        
        glShadeModel(GL_FLAT);
        glColorMask(0, 0, 0, 0);
        
        glCullFace(GL_FRONT);
        
        super.draw(dt);
        
        glCullFace(GL_BACK);
        
        glShadeModel(GL_SMOOTH);
        glColorMask(1, 1, 1, 1);
        
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
    }
    
    void bind(Matrix4x4f invCameraMatrix)
    {
	    glActiveTextureARB(GL_TEXTURE7);
        glMatrixMode(GL_TEXTURE);
        glLoadIdentity();	
        glTranslatef(0.5f, 0.5f, 0.5f);
        glScalef(0.5f, 0.5f, 0.5f);
        glMultMatrixf(projectionMatrix.arrayof.ptr);
        glMultMatrixf(modelViewMatrix.arrayof.ptr);
        glMultMatrixf(invCameraMatrix.arrayof.ptr);
        glMatrixMode(GL_MODELVIEW);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, depthBuffer);
        glActiveTextureARB(GL_TEXTURE0_ARB);
    }
    
    void unbind()
    {
        glActiveTextureARB(GL_TEXTURE7);
        glBindTexture(GL_TEXTURE_2D, 0);
        glDisable(GL_TEXTURE_2D);
        glActiveTextureARB(GL_TEXTURE0_ARB);
    }
    
    ~this()
    {
        if (glIsTexture(depthBuffer))
            glDeleteTextures(1, &depthBuffer);
        glDeleteFramebuffers(1, &fbo);
        Delete(mat);
    }
}
